# This action publishes a package after you push a tag
# See goreleaser documentation
# https://goreleaser.com/ci/actions/
# https://github.com/goreleaser/goreleaser/blob/v1.9.2/www/docs/ci/actions.md
name: Create GitHub Release
on:
  push:
    # run only against tags
    tags:
      - '*'
jobs:
  goreleaser:
    # available runners:
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-18.04
    permissions: 
      contents: write # for creating release
    steps:
      - uses: actions/checkout@v3
        with:
          # git fetch all branches instead of just the ref, and no --depth=1
          # required for goreleaser build unless you use --snapshot or --skip-validate
          fetch-depth: 0
      - name: Fetch all tags
        # this is needed if you use TagBody, TagSubject or TagContents in your template
        run: git fetch --force --tags
      - run: sudo apt-get update && sudo apt-get install -y libgit2-26 libgit2-dev # dependency of git2go
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17.10'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser # either 'goreleaser' (default) or 'goreleaser-pro'
          version: ^1.9.2  # https://github.com/goreleaser/goreleaser/releases
          args: release --debug --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
