name: go test, go vet, go fmt

# triggers
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
  pull_request:
jobs:
  run-tests:
    # available runners:
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y libgit2-26 libgit2-dev
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17.10'
      - run: go test
      - run: go vet
      - run: gofmt -l . || { code=$?; echo Please run go fmt; exit $code; }
