name: go test, go vet, go fmt

# triggers
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
  pull_request:
jobs:
  run-tests:
    # available runners:
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          # git fetch all branches instead of just the ref, and no --depth=1
          # required for goreleaser build unless you use --snapshot or --skip-validate
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.4' # should match GOLANG_CROSS_VERSION in Makefile
      - run: make test
      - run: make vet
      - run: gofmt -l . || { code=$?; echo Please run go fmt; exit $code; }
      - run: make release-dry-run
